### PR TITLE
Fix undefined reference to `_caca_alloc2d`

### LINKED ISSUE #59: Unable to build 0.99.beta20 (common-image.c:164: undefined reference to `_caca_alloc2d')
When looking at packaging the new beta20 release for Gentoo, I hit the following error:
```
x86_64-pc-linux-gnu-gcc -m32 -DHAVE_CONFIG_H -I. -I/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src -I..  -I/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20 -I/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca -I../caca -DLIBCACA=1 -DX_DISPLAY_MISSING=1   -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches     -ggdb3 -UCACA_ENABLE_VISIBILITY -g -O2 -fno-strength-reduce -fomit-frame-pointer -Wall -Wpointer-arith -Wcast-align -Wcast-qual -Wstrict-prototypes -Wshadow -Waggregate-return -Wmissing-prototypes -Wnested-externs -Wsign-compare -fvisibility=hidden -DCACA_ENABLE_VISIBILITY -c -o cacaview-common-image.o `test -f 'common-image.c' || echo '/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/'`common-image.c
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/common-image.c: In function ‘load_image’:
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/common-image.c:164:18: warning: implicit declaration of function ‘_caca_alloc2d’ [-Wimplicit-function-declaration]
  164 |     im->pixels = _caca_alloc2d(im->w, im->h, depth);
      |                  ^~~~~~~~~~~~~
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/common-image.c:164:18: warning: nested extern declaration of ‘_caca_alloc2d’ [-Wnested-externs]
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/common-image.c:164:16: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  164 |     im->pixels = _caca_alloc2d(im->w, im->h, depth);
      |                ^
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -m32  -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches     -ggdb3 -UCACA_ENABLE_VISIBILITY -g -O2 -fno-strength-reduce -fomit-frame-pointer -Wall -Wpointer-arith -Wcast-align -Wcast-qual -Wstrict-prototypes -Wshadow -Waggregate-return -Wmissing-prototypes -Wnested-externs -Wsign-compare -fvisibility=hidden -DCACA_ENABLE_VISIBILITY  -fuse-ld=bfd -Wl,--as-needed -o cacaview cacaview-cacaview.o cacaview-common-image.o ../caca/libcaca.la ../caca/libcaca.la -lncurses -ltinfo
libtool: link: x86_64-pc-linux-gnu-gcc -m32 -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -ggdb3 -UCACA_ENABLE_VISIBILITY -g -O2 -fno-strength-reduce -fomit-frame-pointer -Wall -Wpointer-arith -Wcast-align -Wcast-qual -Wstrict-prototypes -Wshadow -Waggregate-return -Wmissing-prototypes -Wnested-externs -Wsign-compare -fvisibility=hidden -DCACA_ENABLE_VISIBILITY -fuse-ld=bfd -o .libs/cacaview cacaview-cacaview.o cacaview-common-image.o  -Wl,--as-needed ../caca/.libs/libcaca.so -lncursesw -lz -lncurses -ltinfo
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: cacaview-common-image.o: in function `load_image':
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/src/common-image.c:164: undefined reference to `_caca_alloc2d'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:583: cacaview] Error 1
make[2]: Leaving directory '/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20-abi_x86_32.x86/src'
make[1]: *** [Makefile:546: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20-abi_x86_32.x86'
make: *** [Makefile:440: all] Error 2
 * ERROR: media-libs/libcaca-0.99_beta20::gentoo failed (compile phase):
 *   emake failed
```

Seems like the use of _caca_alloc2d was introduced in 96ff990d5e7cda59c73ab1d5bb77ff0c6e3b34f3 and the common-image usage is outside of the library, so might be exacerbated by 726ede64911802b1b5e638b20ce099e55ea4d3c7.

Attached the full [build.log.gz](https://github.com/cacalabs/libcaca/files/7393966/build.log.gz).

### PR DESCRIPTION
**Pull request by JohannesKauffmann**
- Avoid implicit function declaration for `_caca_alloc2d`
- Avoid nested extern declaration for `_caca_alloc2d`
- Fix undefined reference to `_caca_alloc2d`

Fixes #59.

### CODE REVIEW

**Comment by hartwork** [comment]
@JohannesKauffmann the pull request did not work for me, I get this error:

```
In file included from /var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/canvas.c:32:
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca_internals.h:263:9: error: expected ';' before 'void'
  263 | __extern void *_caca_alloc2d(size_t width, size_t height, size_t elem_size);
      |         ^~~~~
      |         ;
make[3]: *** [Makefile:890: libcaca_la-canvas.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca_conio.c:26:
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca_internals.h:263:9: error: expected ';' before 'void'
  263 | __extern void *_caca_alloc2d(size_t width, size_t height, size_t elem_size);
      |         ^~~~~
      |         ;
make[3]: *** [Makefile:876: libcaca_la-caca_conio.lo] Error 1
In file included from /var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/dirty.c:33:
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca_internals.h:263:9: error: expected ';' before 'void'
  263 | __extern void *_caca_alloc2d(size_t width, size_t height, size_t elem_size);
      |         ^~~~~
      |         ;
make[3]: *** [Makefile:897: libcaca_la-dirty.lo] Error 1
In file included from /var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca.c:33:
/var/tmp/portage/media-libs/libcaca-0.99_beta20/work/libcaca-0.99.beta20/caca/caca_internals.h:263:9: error: expected ';' before 'void'
  263 | __extern void *_caca_alloc2d(size_t width, size_t height, size_t elem_size);
      |         ^~~~~
      |         ;
make[3]: *** [Makefile:869: libcaca_la-caca.lo] Error 1
```

Part of the issue seems to be that the function is considered internal but then also references across library boundaries (which conflicts with internal).

I have applied this alternative version in Gentoo for a workaround:
https://github.com/gentoo/gentoo/blob/c24f16c88386dcf87e8485ab8df30f4084b92ab7/media-libs/libcaca/files/libcaca-0.99_beta20-linking.patch . It effectively makes the function public API.
