### ISSUE TITLE
Tests fail to compile with cppunit >= 1.14 and GCC 5

### ISSUE THREAD

**Issue by sbraz** [cacalabs/libcaca#26]
Hi,
It seems that with cppunit 1.14 and GCC 5.40, tests fail to compile. Adding `-std=c++11` to `CXXFLAGS` fixes the problem.
```
make  all-recursive
make[1]: Entering directory '/tmp/libcaca'
Making all in kernel
make[2]: Entering directory '/tmp/libcaca/kernel'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/libcaca/kernel'
Making all in caca
make[2]: Entering directory '/tmp/libcaca/caca'
Making all in .
make[3]: Entering directory '/tmp/libcaca/caca'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/tmp/libcaca/caca'
Making all in t
make[3]: Entering directory '/tmp/libcaca/caca/t'
  CXX      caca_test-canvas.o
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/type_traits:35:0,
                 from /usr/include/cppunit/tools/StringHelper.h:7,
                 from /usr/include/cppunit/TestAssert.h:8,
                 from /usr/include/cppunit/TestCase.h:6,
                 from /usr/include/cppunit/TestCaller.h:5,
                 from /usr/include/cppunit/extensions/HelperMacros.h:9,
                 from canvas.cpp:15:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/cppunit/TestAssert.h:8:0,
                 from /usr/include/cppunit/TestCase.h:6,
                 from /usr/include/cppunit/TestCaller.h:5,
                 from /usr/include/cppunit/extensions/HelperMacros.h:9,
                 from canvas.cpp:15:
/usr/include/cppunit/tools/StringHelper.h:22:15: error: ‘enable_if’ in namespace ‘std’ does not name a template type
 typename std::enable_if<!std::is_enum<T>::value, std::string>::type toString(const T& x)
               ^
/usr/include/cppunit/tools/StringHelper.h:22:24: error: expected unqualified-id before ‘<’ token
 typename std::enable_if<!std::is_enum<T>::value, std::string>::type toString(const T& x)
                        ^
/usr/include/cppunit/tools/StringHelper.h:31:15: error: ‘enable_if’ in namespace ‘std’ does not name a template type
 typename std::enable_if<std::is_enum<T>::value, std::string>::type toString(const T& x)
               ^
/usr/include/cppunit/tools/StringHelper.h:31:24: error: expected unqualified-id before ‘<’ token
 typename std::enable_if<std::is_enum<T>::value, std::string>::type toString(const T& x)
                        ^
In file included from /usr/include/cppunit/Exception.h:4:0,
                 from /usr/include/cppunit/TestCaller.h:4,
                 from /usr/include/cppunit/extensions/HelperMacros.h:9,
                 from canvas.cpp:15:
/usr/include/cppunit/TestAssert.h: In static member function ‘static std::__cxx11::string CppUnit::assertion_traits<T>::toString(const T&)’:
/usr/include/cppunit/TestAssert.h:74:16: error: ‘toString’ is not a member of ‘CppUnit::StringHelper’
         return CPPUNIT_NS::StringHelper::toString(x);
                ^
In file included from /usr/include/cppunit/extensions/HelperMacros.h:9:0,
                 from canvas.cpp:15:
/usr/include/cppunit/TestCaller.h: At global scope:
/usr/include/cppunit/TestCaller.h:159:37: error: ‘std::function’ has not been declared
   TestCaller(std::string name, std::function<void()> test_function, Fixture* fixture):
                                     ^
/usr/include/cppunit/TestCaller.h:159:45: error: expected ‘,’ or ‘...’ before ‘<’ token
   TestCaller(std::string name, std::function<void()> test_function, Fixture* fixture):
                                             ^
/usr/include/cppunit/TestCaller.h:200:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<void()> m_test_function;
        ^
/usr/include/cppunit/TestCaller.h: In constructor ‘CppUnit::TestCaller<Fixture>::TestCaller(std::__cxx11::string, CppUnit::TestCaller<Fixture>::TestMethod)’:
/usr/include/cppunit/TestCaller.h:121:6: error: class ‘CppUnit::TestCaller<Fixture>’ does not have any field named ‘m_test_function’
      m_test_function( std::bind(test, m_fixture) )
      ^
/usr/include/cppunit/TestCaller.h:121:23: error: ‘bind’ is not a member of ‘std’
      m_test_function( std::bind(test, m_fixture) )
                       ^
/usr/include/cppunit/TestCaller.h: In constructor ‘CppUnit::TestCaller<Fixture>::TestCaller(std::__cxx11::string, CppUnit::TestCaller<Fixture>::TestMethod, Fixture&)’:
/usr/include/cppunit/TestCaller.h:138:6: error: class ‘CppUnit::TestCaller<Fixture>’ does not have any field named ‘m_test_function’
      m_test_function( std::bind(test, &fixture) )
      ^
/usr/include/cppunit/TestCaller.h:138:23: error: ‘bind’ is not a member of ‘std’
      m_test_function( std::bind(test, &fixture) )
                       ^
/usr/include/cppunit/TestCaller.h: In constructor ‘CppUnit::TestCaller<Fixture>::TestCaller(std::__cxx11::string, CppUnit::TestCaller<Fixture>::TestMethod, Fixture*)’:
/usr/include/cppunit/TestCaller.h:155:6: error: class ‘CppUnit::TestCaller<Fixture>’ does not have any field named ‘m_test_function’
      m_test_function( std::bind(test, fixture) )
      ^
/usr/include/cppunit/TestCaller.h:155:23: error: ‘bind’ is not a member of ‘std’
      m_test_function( std::bind(test, fixture) )
                       ^
/usr/include/cppunit/TestCaller.h: In constructor ‘CppUnit::TestCaller<Fixture>::TestCaller(std::__cxx11::string, int)’:
/usr/include/cppunit/TestCaller.h:162:17: error: ‘fixture’ was not declared in this scope
       m_fixture(fixture),
                 ^
/usr/include/cppunit/TestCaller.h:163:7: error: class ‘CppUnit::TestCaller<Fixture>’ does not have any field named ‘m_test_function’
       m_test_function(test_function)
       ^
/usr/include/cppunit/TestCaller.h:163:23: error: ‘test_function’ was not declared in this scope
       m_test_function(test_function)
                       ^
/usr/include/cppunit/TestCaller.h: In member function ‘void CppUnit::TestCaller<Fixture>::runTest()’:
/usr/include/cppunit/TestCaller.h:175:23: error: there are no arguments to ‘m_test_function’ that depend on a template parameter, so a declaration of ‘m_test_function’ must be available [-fpermissive]
       m_test_function();
                       ^
/usr/include/cppunit/TestCaller.h:175:23: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from /usr/include/cppunit/Exception.h:4:0,
                 from /usr/include/cppunit/TestCaller.h:4,
                 from /usr/include/cppunit/extensions/HelperMacros.h:9,
                 from canvas.cpp:15:
/usr/include/cppunit/extensions/TestNamer.h: In member function ‘std::__cxx11::string CppUnit::TestNamer::getTestNameFor(const string&, const E&) const’:
/usr/include/cppunit/extensions/TestNamer.h:70:69: error: ‘toString’ is not a member of ‘CppUnit::StringHelper’
       return getTestNameFor(testMethodName) + " with parameter: " + CPPUNIT_NS::StringHelper::toString(val);
                                                                     ^
In file included from canvas.cpp:15:0:
canvas.cpp: In static member function ‘static CppUnit::TestSuite* CanvasTest::suite()’:
canvas.cpp:29:5: error: ‘unique_ptr’ is not a member of ‘std’
     CPPUNIT_TEST_SUITE_END();
     ^
canvas.cpp:29:5: error: expected primary-expression before ‘>’ token
     CPPUNIT_TEST_SUITE_END();
     ^
canvas.cpp:29:5: error: ‘guard’ was not declared in this scope
     CPPUNIT_TEST_SUITE_END();
     ^
In file included from /usr/include/cppunit/extensions/HelperMacros.h:9:0,
                 from canvas.cpp:15:
/usr/include/cppunit/TestCaller.h: In instantiation of ‘void CppUnit::TestCaller<Fixture>::runTest() [with Fixture = CanvasTest]’:
canvas.cpp:109:44:   required from here
/usr/include/cppunit/TestCaller.h:175:22: error: ‘m_test_function’ was not declared in this scope
       m_test_function();
                      ^
make[3]: *** [Makefile:753: caca_test-canvas.o] Error 1
make[3]: Leaving directory '/tmp/libcaca/caca/t'
make[2]: *** [Makefile:1176: all-recursive] Error 1
make[2]: Leaving directory '/tmp/libcaca/caca'
make[1]: *** [Makefile:543: all-recursive] Error 1
make[1]: Leaving directory '/tmp/libcaca'
make: *** [Makefile:437: all] Error 2

```
